# base image
FROM node:14

# set working directory

WORKDIR /usr/src/app/frontend

COPY package*.json ./

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

# add app
COPY . .

EXPOSE 4200

CMD ["npm", "run", "dev:ssr"]
